script:
  - mvn clean verify
  - pwd
  - ls $HOME/build/BastienCUENOT/sample-application-students/sample-application-http-api-server/target/
cache:
 directories:
 - "$HOME/.m2"
 - "$HOME/.sonar/cache"

services:
  - docker

after_success:
  - docker build -t changelogimage $HOME/build/BastienCUENOT/sample-application-students/sample-application-db-changelog-job/
  - docker build -t httpserverimage $HOME/build/BastienCUENOT/sample-application-students/sample-application-http-api-server/ 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag changelogimage $DOCKER_USERNAME/changelogimage:1.0
  - docker push $DOCKER_USERNAME/changelogimage
  - docker tag httpserverimage $DOCKER_USERNAME/httpserverimage:1.0
  - docker push $DOCKER_USERNAME/httpserverimage
notifications:
 email:
   on_failure: never

