addons:
  sonarcloud:
    organization: "bastiencuenot"
    token:
      secure: 4a2ea8de666ac28ebaa69046443291985543e5e1

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BastienCUENOT_sample-application-students
cache:
 directories:
 - "$HOME/.m2"
 - "$HOME/.sonar/cache"

services:
  - docker

after_success:
  - docker build -t changelogimage $HOME/build/BastienCUENOT/sample-application-students/sample-application-db-changelog-job/
  - docker build -t httpserverimage $HOME/build/BastienCUENOT/sample-application-students/sample-application-http-api-server/ 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag changelogimage $DOCKER_USERNAME/changelogimage:1.0
  - docker push $DOCKER_USERNAME/changelogimage
  - docker tag httpserverimage $DOCKER_USERNAME/httpserverimage:1.0
  - docker push $DOCKER_USERNAME/httpserverimage
notifications:
 email:
   on_failure: never

